### ISSUE TITLE
[Q] Each cluster node will serve as a server, right?

### ISSUE THREAD

**Issue by kseistrup** [geniltodallo/prosody-mod_cluster#1]
Suppose your main XMPP domain is `example.org`, and the three cluster nodes are `sv0[1-3].example.org`, then each of the cluster nodes should be configured to answer for `example.org`, right?

**Comment by geniltodallo** [comment]
Hello! Yes, for use with the same domain on the nodes. Still need to finish ssl/tls connection.

**Comment by kseistrup** [comment]
Great, thanks!

> Still need to finish ssl/tls connection.

My planned nodes are connected in an encrypted VPN (WireGuard), so for now the missing TLS is of less concern.

It's really great to see this module after all these years. :+1:

**Comment by geniltodallo** [comment]
Ok thanks. Let me know if you find any issue.

**Comment by geniltodallo** [comment]
How many simultaneous users does your prosody have @kseistrup?

**Comment by kseistrup** [comment]
Not a lot, it's just a self-hosted server (soon: cluster) for a handful of users (who may each have several devices using the same account).
